apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app.kubernetes.io/name: api-server
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  # - port: 443
  #   protocol: TCP
  #   name: https
  selector:
      app.kubernetes.io/name: api-server
